package com.vortexscape.launcher;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The update manifest.
 *
 * {
 *   "channel": "live",
 *   "version": "2.2",
 *   "jar":     "https://vortexidle.com/client/rs2client.jar",
 *   "sha256":  "abc123..."
 * }
 *
 * Parsed by hand rather than with a JSON library: the launcher is the one
 * artifact players cannot auto-update, so it carries no dependencies. The file
 * is generated by our own CI and is a flat map of strings, so a field scan is
 * sufficient. It is deliberately strict - anything unexpected throws rather than
 * being quietly tolerated, because the result decides what code gets executed.
 */
final class Manifest {
    final String channel;
    final String version;
    final String jarUrl;
    final String sha256;

    private Manifest(String channel, String version, String jarUrl, String sha256) {
        this.channel = channel;
        this.version = version;
        this.jarUrl = jarUrl;
        this.sha256 = sha256;
    }

    static Manifest fetch(String url) throws Exception {
        return parse(new String(LauncherIO.read(url), StandardCharsets.UTF_8));
    }

    static Manifest parse(String json) throws IOException {
        String channel = field(json, "channel");
        String version = field(json, "version");
        String jar = field(json, "jar");
        String sha = field(json, "sha256");

        if (channel == null || version == null || jar == null || sha == null) {
            throw new IOException("manifest is missing one of: channel, version, jar, sha256");
        }
        if (!sha.matches("(?i)[0-9a-f]{64}")) {
            throw new IOException("manifest sha256 is not a 64 character hex digest: " + sha);
        }
        // Keep channel usable as a directory name.
        if (!channel.matches("[A-Za-z0-9._-]{1,32}")) {
            throw new IOException("manifest channel is not a safe name: " + channel);
        }
        return new Manifest(channel, version, jar, sha);
    }

    private static String field(String json, String name) {
        Matcher m = Pattern.compile("\"" + Pattern.quote(name) + "\"\\s*:\\s*\"([^\"]*)\"").matcher(json);
        return m.find() ? m.group(1) : null;
    }
}
